package com.example.caobatruckscontrol.data.model

import com.google.firebase.firestore.Exclude
import com.google.firebase.firestore.IgnoreExtraProperties

@IgnoreExtraProperties
data class Box(
    var id: String = "", // Optional if you have an ID generated by Firebase
    var mark: String = "",
    var template: String = "",
    var modelYear: String = "",
    var licensePlate: String = "",
    var color: String = "",
    var isActive: Boolean = true,
    var circulationCardFolio: String = "",
    var insurancePolicy: String = "",
    var insuranceCompany: String = "",
    var imageUrl: String = "", // URL to the image of the box (optional)
    var insuranceImageUrl: String = "", // URL to the image of the insurance policy (optional)
    var licensePlatePhotoUrl: String? = null, // URL to the image of license plate
    var boxPhotoUrl: String? = null, // URL to the image of the box itself
    var circulationCardFolioPhotoUrl: String? = null, // URL to the image of circulation card folio
    var insurancePolicyPhotoUrl: String? = null // URL to the image of insurance policy
) {
    @Exclude
    fun toMap(): Map<String, Any?> {
        return mapOf(
            "mark" to mark,
            "template" to template,
            "modelYear" to modelYear,
            "licensePlate" to licensePlate,
            "color" to color,
            "circulationCardFolio" to circulationCardFolio,
            "insurancePolicy" to insurancePolicy,
            "insuranceCompany" to insuranceCompany,
            "imageUrl" to imageUrl,
            "insuranceImageUrl" to insuranceImageUrl,
            "licensePlatePhotoUrl" to licensePlatePhotoUrl,
            "boxPhotoUrl" to boxPhotoUrl,
            "circulationCardFolioPhotoUrl" to circulationCardFolioPhotoUrl,
            "insurancePolicyPhotoUrl" to insurancePolicyPhotoUrl
        )
    }
}
